import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import Footer from '../../../components/Footer/Footer'
import Box from '@mui/material/Box'
import useMediaQuery from '@mui/material/useMediaQuery';
import NavBar from '../../../components/NavBar/NavBar';
import styles from './Layout.module.scss';

export default function Layout({children}) {
  const matchesLg = useMediaQuery('(min-width:1200px)');

  return (
    <>
      <Head>
        <title>Vesta Inmobiliario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <NavBar/>
      <Box className={styles.bodyPage}>
        <Box className={styles.page}>
          {children}
        </Box>
        <Footer/>
      </Box>
    </>
  )
}